# Site settings
title: Ricardo Ochoa Sosa
email: ochoasosaricardo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Common tasks, functions and processes for data analysis and 
  visualization in R.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ricardoochoa.github.io" # the base hostname & protocol for your site
twitter_username: ricardoochoa
github_username:  ricardoochoa

# Build settings
markdown: kramdown
